simple_rnn:
  data_dir: "pykin/test"
  save: True
  units: 12
  batch_size: 16
  epochs: 10
  verbose: 1
  lr: 0.01
lstm:
  data_dir: "pykin/test"
  save: True
  batch_size: 250
  epochs: 10
  verbose: 1
  lr: 0.01
