x_train_file: "x_train_mil.npy"
y_train_file: "y_train_mil.npy"
x_test_file: "x_test_mil.npy"
y_test_file: "y_test_mil.npy"
save: True
batch_size: 500
epochs: 100
verbose: 1
validation_split: 0.0
shuffle: True
initial_epoch: 0
validation_freq: 1
lr: 0.1
filters1: 1000
filters2: 800
units1: 800
units2: 600
units3: 400
units4: 200
units5: 100
