simple_mlp:
  data_dir: "pykin/test"
  save: True
  units: 160
  batch_size: 32
  epochs_to_change: [50, 150, 300]
  lr: 0.001
  epochs: 300
  verbose: 1
  orient_factor: 0.5
  pos_factor: 0.5
seven_subnet_mlp:
  data_dir: "pykin/test"
  save: True
  units1: 16
  units2: 272
  units3: 496
  units4: 496
  units5: 272
  units6: 496
  units7: 496
  batch_size: 32
  lr: 0.01
  epochs: 5
  verbose: 0
