x_train_file: "x_train.npy"
y_train_file: "y_train.npy"
x_test_file: "x_test.npy"
y_test_file: "y_test.npy"
save: True
batch_size: 32
epochs: 100
verbose: 0
validation_split: 0.0
shuffle: True
initial_epoch: 0
validation_freq: 1
