simple_mlp:
  data_dir: "pykin/test"
  save: True
  units: 160
  batch_size: 64
  threshold: 0.17
  lr: 0.1
  epochs: 400
  verbose: 1
  orient_factor: 0.5
  pos_factor: 0.5
seven_subnet_mlp:
  data_dir: "pykin/test"
  save: True
  units1: 16
  units2: 272
  units3: 496
  units4: 496
  units5: 272
  units6: 496
  units7: 496
  batch_size: 32
  lr: 0.01
  epochs: 5
  verbose: 0
