x_train_file: "x_train_mil.npy"
y_train_file: "y_train_mil.npy"
x_test_file: "x_test_mil.npy"
y_test_file: "y_test_mil.npy"
simple_mlp:
  save: True
  units: 160
  batch_size: 16
  lr: 0.001
  epochs: 100
  verbose: 1
seven_subnet_mlp:
  save: True
  units1: 16
  units2: 272
  units3: 496
  units4: 496
  units5: 272
  units6: 496
  units7: 496
  batch_size: 32
  lr: 0.01
  epochs: 5
  verbose: 0
